name: Playwright Tests
on:
  push:
    branches: [ blazedemo ]
  pull_request:
    branches: [ blazedemo ]

permissions:
 contents: write
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install --force
      
    - name: Install Allure
      run: npm install -g allure-playwright allure-commandline --save-dev
      
    - name: Cleanup old reports
      run: npm run allureclean
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npm run web
      continue-on-error: true
      
    - name: Generate Allure Report
      run: npm run alluregenerate
      continue-on-error: true

    - name: Allure Open
      run: npm run allureopen
      continue-on-error: true
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
       name: Full Report
       path: ${{ github.workspace }}/*

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: jagadeeshmadhura2@gmail.com
          password: jmqjvkcghbeudpad
          subject: Test Automation Suite Report
          to: jagadeesh@qtsolv.com
          from: QA Automation <jagadeeshmadhura2@gmail.com>
          secure: true
          html_body: file://${{ github.workspace }}/playwright-report/index.html
          attachments: ${{ github.workspace }}/playwright-report/index.html
