name: Playwright Tests
on:
  push:
    branches: [ blazedemo ]
  pull_request:
    branches: [ blazedemo ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
      
    - name: Install Allure
      run: npm i -D allure-playwright

    - name: Cleanup old reports
      run: npm run allureclean
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npm run web
      continue-on-error: true
      
    - name: Allure Report Generation
      run: npm run alluregenerate
      continue-on-error: true
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
          name: Report
          path: ${{ github.workspace }}/allure-report/

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: jagadeeshmadhura2@gmail.com
          password: zefkubiaatpaqyso
          subject:  Test Automation Suite Report
          to: jagadeesh@qtsolv.com
          from: Automation Team<jagadeeshmadhura2@gmail.com>
          secure: true
          html_body: file://${{ github.workspace }}/allure-report/index.html
          attachments: ${{github.workspace}}/allure-report/index.html
