name: Playwright Tests
on:
  push:
    branches: [ blazedemo ]
  pull_request:
    branches: [ blazedemo ]

permissions:
 contents: write
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install --force
      
    - name: Install Allure
      run: npm i -D allure-playwright

    - name: Install Allure command line
      run: npm install -g allure-commandline --save-dev
      
    - name: Cleanup old reports
      run: npm run allureclean
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npm run web
      continue-on-error: true
      
    - name: Generate Allure Report
      run: npm run alluregenerate
      continue-on-error: true

    - name: Get current timestamp
      id: ts
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

    - name: Create report directory
      run: |
       mkdir -p gh-pages/allure-report-${{ steps.ts.outputs.timestamp }}
       cp -r ./allure-report/* gh-pages/allure-report-${{ steps.ts.outputs.timestamp }}/

    - name: Commit and push new report
      run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout gh-pages || git checkout --orphan gh-pages
          mkdir -p reports
          cp -r gh-pages/allure-report-${{ steps.ts.outputs.timestamp }} reports/
          git add reports/
          git commit -m "Add Allure report from ${{ steps.ts.outputs.timestamp }}"
          git push origin gh-pages

    - name: Remove old reports
      run: |
          git checkout gh-pages
          cd reports
          ls -d allure-report-* | sort -r | tail -n +6 | xargs rm -rf
          git add .
          git commit -m "Remove old Allure reports"
          git push origin gh-pages

    - name: Deploy Allure report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: reports/allure-report-${{ env.timestamp }}
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
       name: Report
       path: allure-report.zip

    - name: Send email with report link
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "Allure Report"
          body: "The Allure report is available at: https://jagadeeshqtsolv.github.io/playwright-typescript/reports/allure-report-${{ env.timestamp }}/index.html"
          to: "jagadeesh@qtsolv.com"
          from: "jagadeesh@qtsolv.com"
