name: Playwright Tests
on:
  push:
    branches: [ blazedemo ]
  pull_request:
    branches: [ blazedemo ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install --force
      
    - name: Install Allure
      run: npm i -D allure-playwright

    - name: Install Allure command line
      run: npm install -g allure-commandline --save-dev
      
    - name: Cleanup old reports
      run: npm run allureclean
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npm run web
      continue-on-error: true

    - name: Wait for 5 seconds
      run: sleep 5
      
    - name: Generate Allure Report
      run: npm run alluregenerate
      continue-on-error: true
      
    - name: Zip Allure Report
      run: zip -r allure-report.zip ${{ github.workspace }}/allure-report

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
       name: Report
       path: allure-report.zip

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: jagadeeshmadhura2@gmail.com
          password: zefkubiaatpaqyso
          subject:  Test Automation Suite Report
          to: jagadeesh@qtsolv.com
          from: Automation Team<jagadeeshmadhura2@gmail.com>
          secure: true
          html_body: <html><body> <p>Please find automation report </p></body> </html>
          attachments: ${{github.workspace}}/allure-report/index.html
