name: Playwright Tests
on:
  push:
    branches: [ blazedemo ]
  pull_request:
    branches: [ blazedemo ]

permissions:
 contents: write
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install --force
      
    - name: Install Allure
      run: npm i -D allure-playwright

    - name: Install Allure command line
      run: npm install -g allure-commandline --save-dev
      
    - name: Cleanup old reports
      run: npm run allureclean
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npm run web
      continue-on-error: true
      
    - name: Generate Allure Report
      run: npm run alluregenerate
      continue-on-error: true

    - name: Deploy Allure report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: "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"
        publish_dir: ${{github.workspace}}/allure-report

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
       name: Report
       path: allure-report.zip

    - name: Send email with report link
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "Allure Report"
          body: "The Allure report is available at: https://jagadeeshqtsolv.github.io/gh-pages/index.html"
          to: "jagadeesh@qtsolv.com"
          from: "jagadeesh@qtsolv.com"
